### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by thebitbrine** [leviwheatcroft/metalsmith-google-drive#1]
HI, i'm new to Node.JS and i have a problem with getting the metalsmith google drive to run.
I tried to install the the dependencies from package.json and it went fine but i couldn't get the /test/index.js to work.  Here's the error i get:
```
(function (exports, require, module, __filename, __dirname) { import plugin from '../lib'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3

```

**Comment by leviwheatcroft** [comment]
Hey,

The unexpected token it's talking about is an ES6 import statement. ES6 is javascript spec which isn't fully implemented by node, so you run it through a transpiler like babel. The package is configured to do this for you. If you `npm run` you'll see a list of the commands the package is configured with, `npm run test` will run `/test/index.js` in the right test environment (using mocha & babel). This isn't the whole story so you should take a look at the npm docs. Sorry if I've misunderstood your problem.

I'm not certain about this but I have a feeling this plugin may be broken. It's been a long time since I've used it and at some point I remember thinking that some change to the google API had broken it. Let me know how you go anyway.
